//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CafeEntities : DbContext
    {
        public CafeEntities()
            : base("name=CafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PersonelBilgileri> PersonelBilgileri { get; set; }
        public virtual DbSet<PersonelGiris> PersonelGiris { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Masa> Masa { get; set; }
        public virtual DbSet<MasaKategori> MasaKategori { get; set; }
        public virtual DbSet<MenuKategori> MenuKategori { get; set; }
        public virtual DbSet<Odeme> Odeme { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetay { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
    }
}
