//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int id { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<int> İptalMi { get; set; }
        public Nullable<System.DateTime> iptalTarihi { get; set; }
    }
}
