//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int id { get; set; }
        public Nullable<int> MasaId { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<System.DateTime> AcilisTarihi { get; set; }
        public Nullable<int> KapandiMi { get; set; }
        public Nullable<System.DateTime> KapanisTarihi { get; set; }
    }
}
